### ISSUE TITLE
NoMethodError (undefined method `where' for []:Array):

### ISSUE THREAD

**Issue by nazarhussain** [netzke/netzke-basepack#155]
I am facing problem in implementing simple grid component. 

```
NoMethodError (undefined method `where' for []:Array):
  netzke-basepack (0.10.1) lib/netzke/basepack/data_adapters/active_record_adapter.rb:341:in `get_relation'
  netzke-basepack (0.10.1) lib/netzke/basepack/data_adapters/active_record_adapter.rb:48:in `get_records'
  netzke-basepack (0.10.1) lib/netzke/basepack/grid/services.rb:82:in `get_records'
  netzke-basepack (0.10.1) lib/netzke/basepack/grid/services.rb:9:in `block in read'
  netzke-basepack (0.10.1) lib/netzke/basepack/grid/services.rb:8:in `tap'
  netzke-basepack (0.10.1) lib/netzke/basepack/grid/services.rb:8:in `read'
  netzke-basepack (0.10.1) lib/netzke/basepack/grid/endpoints.rb:89:in `attempt_operation'
  netzke-basepack (0.10.1) lib/netzke/basepack/grid/endpoints.rb:9:in `block (2 levels) in <module:Endpoints>'
```

Here is my grid code

```ruby
class CitiesGrid < Netzke::Basepack::Grid
  def configure(c)
    c.persistence = true
    c.model = 'City'
    c.title = 'Cities'
    c.columns = [:code, :title, {name: :description, flex: 1}, :created_at, :updated_at]
    c.enable_edit_inline = false
    c.enable_add_inline = false
    super
  end

  def preconfigure_record_window(c)
    super
    c.form_config.klass = CitiesForm
  end

  include ::PgGridTweaks
end
```

This project was already working, I just updated the netzke version to `0.10.1`.

Please help me to get running my project.

**Comment by mxgrn** [comment]
Just checked it:

[1] pry(main)> Book.all.class
=> Book::ActiveRecord_Relation

Maybe this changed again in Rails. Should be working now, reopen if otherwise. Closing.
